version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb_learn_go_codevoweb
    env_file:
      - ../app.env

    ports:
      - "6000:27017"
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis_learn_go_codevoweb
    ports:
      - "6379:6379"
    volumes:
      - redisDB:/data
volumes:
  mongodb:
  redisDB:
